"""add literature to the methodics

Revision ID: 396d8c4e877d
Revises: ebbdaa9a3090
Create Date: 2018-11-13 21:03:15.279703

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '396d8c4e877d'
down_revision = 'ebbdaa9a3090'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('methodics', sa.Column('literature', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('methodics', 'literature')
    # ### end Alembic commands ###
