"""timing work

Revision ID: 7af74e40a153
Revises: 396d8c4e877d
Create Date: 2018-11-19 19:26:51.406733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7af74e40a153'
down_revision = '396d8c4e877d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('method_timing', sa.Column('method_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'method_timing', 'methodics', ['method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'method_timing', type_='foreignkey')
    op.drop_column('method_timing', 'method_id')
    # ### end Alembic commands ###
