"""first add method change

Revision ID: 87086b5d319f
Revises: cb7ac59fa08f
Create Date: 2018-11-22 14:19:34.578816

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87086b5d319f'
down_revision = 'cb7ac59fa08f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('methodics_timing_id_fkey', 'methodics', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('methodics_timing_id_fkey', 'methodics', 'method_timing', ['timing_id'], ['id'])
    # ### end Alembic commands ###
