"""timing work 3

Revision ID: cb7ac59fa08f
Revises: 69eaa0e2d726
Create Date: 2018-11-19 19:50:15.433419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cb7ac59fa08f'
down_revision = '69eaa0e2d726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('method_timing', sa.Column('duration', sa.Integer(), nullable=False))
    op.drop_column('method_timing', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('method_timing', sa.Column('description', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
    op.drop_column('method_timing', 'duration')
    # ### end Alembic commands ###
