"""first

Revision ID: ebbdaa9a3090
Revises: 
Create Date: 2018-11-13 00:42:19.796539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ebbdaa9a3090'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(length=256), nullable=False),
    sa.Column('parrent_cat', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('method_timing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=64), nullable=True),
    sa.Column('phone_num', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=254), nullable=True),
    sa.Column('curr_job_place', sa.String(length=254), nullable=True),
    sa.Column('karma', sa.Integer(), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('profile_image', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone_num'), 'users', ['phone_num'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('methodics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('publish_date', sa.DateTime(), nullable=False),
    sa.Column('change_date', sa.DateTime(), nullable=True),
    sa.Column('title', sa.String(length=256), nullable=False),
    sa.Column('short_desc', sa.Text(), nullable=False),
    sa.Column('target', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('consumables', sa.Text(), nullable=True),
    sa.Column('timing_id', sa.Integer(), nullable=False),
    sa.Column('method_label_image', sa.String(length=64), nullable=False),
    sa.Column('presentation', sa.String(length=64), nullable=True),
    sa.Column('images', sa.Text(), nullable=True),
    sa.Column('music', sa.Text(), nullable=True),
    sa.Column('video', sa.Text(), nullable=True),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('tags', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['category'], ['categories.id'], ),
    sa.ForeignKeyConstraint(['timing_id'], ['method_timing.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('timing_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('method_timing_id', sa.Integer(), nullable=False),
    sa.Column('step_duration', sa.Integer(), nullable=False),
    sa.Column('step_desc', sa.String(length=256), nullable=False),
    sa.Column('step_result', sa.Text(), nullable=False),
    sa.Column('step_label_image', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['method_timing_id'], ['method_timing.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('timing_steps')
    op.drop_table('methodics')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone_num'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('method_timing')
    op.drop_table('categories')
    # ### end Alembic commands ###
